apiVersion: v2
name: firstchart
description: Helm chart for AppAPI with PostgreSQL and Redis dependencies
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 18.5.6
    repository: "registry-1.docker.io/bitnamicharts/postgresql:18.5.6"
    condition: postgresql.enabled
  - name: redis
    version: 25.3.2
    repository: "oci://registry-1.docker.io/bitnamicharts/redis:25.3.2"
    condition: redis.enabled