apiVersion: v2
name: firstchart
description: Helm chart for AppAPI with PostgreSQL and Redis dependencies
type: application
version: 0.1.0
appVersion: "1.0.0"



dependencies:
  - name: postgresql
    version: 17.2.0-debian-12-r0 
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: redis
    version: 7.4.1-debian-12-r2 
    repository: oci://registry-1.docker.io/bitnamicharts
