replicaCount: 1

image:
  repository: yasin313/appapi
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

app:
  message: "connected successfully"

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 16.3.0-debian-12-r8
  auth:
    username: appuser
    password: apppass
    database: appdb
  primary:
    service:
      ports:
        postgresql: 5432

redis:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: 7.2.4-debian-12-r9
  architecture: standalone
  auth:
    enabled: false
  master:
    service:
      ports:
        redis: 6379

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
