replicaCount: 1

image:
  repository: yasin313/appapi
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

app:
  message: "connected to DB successfully"

postgresql:
  enabled: true
  auth:
    username: appuser
    password: apppass
    database: appdb
  primary:
    service:
      ports:
        postgresql: 5432

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    service:
      ports:
        redis: 6379

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
