replicaCount: 1

image:
  repository: yasin313/yasin-dev-test
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

app:
  message: "connected successfully"

postgresql:
  enabled: true
  # -- image:
    #registry: docker.io
  repository: registry-1.docker.io/bitnamicharts/postgresql:18.5.6
    #tag: "17.2.0-debian-12-r0" 
  auth:
    username: appuser
    password: apppass
    database: appdb
  primary:
    service:
      ports:
        postgresql: 5432
    persistence:
      enabled: false

redis:
  enabled: true
  #image:
   # registry: docker.io
  repository: bitnamilegacy/redis
    #tag: "7.4.1-debian-12-r2"
  architecture: standalone
  auth:
    enabled: false
  master:
    service:
      ports:
        redis: 6379
    persistence:
      enabled: false
  replica:
    replicaCount: 0

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}