apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-api.name" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ include "app-api.postgresHost" . }}
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgresql.auth.database }}
  DB_USER: {{ .Values.postgresql.auth.username }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password }}
  REDIS_HOST: {{ include "app-api.redisHost" . }}
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_PASSWORD: ""
  APP_MESSAGE: {{ .Values.app.message | quote }}
