apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "app-api.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
