apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firstchart.fullname" . }}
  labels:
    {{- include "firstchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "firstchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "firstchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: appapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: APP_MESSAGE
              value: {{ .Values.app.message | quote }}

            - name: POSTGRES_HOST
              value: {{ include "firstchart.postgresqlHost" . | quote }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "firstchart.fullname" . }}-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "firstchart.fullname" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "firstchart.fullname" . }}-secret
                  key: POSTGRES_PASSWORD

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "firstchart.fullname" . }}-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "firstchart.fullname" . }}-secret
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "firstchart.fullname" . }}-secret
                  key: REDIS_PASSWORD
                  optional: true
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 16 }}
