apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firstchart.fullname" . }}-secret
  labels:
    {{- include "firstchart.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}

  REDIS_HOST: {{ "firstchart-redis-master" | b64enc | quote }}
  REDIS_PORT: {{ "6379" | b64enc | quote }}