ingress-nginx:
  controller:
    replicaCount: 1

    nodeSelector:
      kubernetes.io/hostname: talos-test-yasin2

    service:
      type: NodePort
      nodePorts:
        http: 30090
        https: 30444

    ingressClassResource:
      name: nginx
      enabled: true
      default: true

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    defaultBackend:
      enabled: true
