apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-api
  namespace: argocd
spec:
  project: main
  source:
    repoURL: https://github.com/yasin-2000-cyber/test-cluster.git
    targetRevision: HEAD
    path: charts/apps/app-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
